export const FETCH_MANAGEMENT = 'FETCH_MANAGEMENT'
export const ADD_MANAGEMENT = 'ADD_MANAGEMENT'
export const EDIT_MANAGEMENT = 'EDIT_MANAGEMENT'
export const DELETE_MANAGEMENT = 'DELETE_MANAGEMENT'
