export const FETCH_MANAGEMENT_SUCCESS = 'FETCH_MANAGEMENT_SUCCESS'
export const FETCH_MANAGEMENT_FAILURE = 'FETCH_MANAGEMENT_FAILURE'
export const DELETE_MANAGEMENT_SUCCESS = 'DELETE_MANAGEMENT_SUCCESS'
export const DELETE_MANAGEMENT_FAILURE = 'DELETE_MANAGEMENT_FAILURE'
